title: Punita Verma
description: "Senior Data Scientist | AI Enthusiast | Writer"
baseurl: ""  # Since your site is at the root, this remains empty
show_downloads: true
#url: "https://punitaverma.github.io"
theme: academic-jekyll-theme

# Add Navigation Tabs (used in the layout)
nav_links:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"
    
#markdown: kramdown
