title: "Punita Verma"
description: "Senior Data Scientist | AI Enthusiast | Writer"
baseurl: ""
url: "https://punitaverma.github.io"

theme: jekyll-theme-minimal

# Add Navigation Tabs (used in the layout)
nav_links:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects/"
  - title: "Blog"
    url: "/blog/"
  - title: "Projects"
    url: "/projects/"


markdown: kramdown
